name: Packaging

on:
  push:
    tags:
      # normal releases semvar
      - "v[0-9]+.[0-9]+.[0-9]+"
      # dev builds like dev-YYYY.MM.DD-0, where 0 is the build number for that day
      - "dev-[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]-[0-9]+"

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          architecture: "x64"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Linux Executable
        shell: bash
        run: python package.py

      - name: Zip Executable
        shell: bash
        run: zip -yr bsw-x86_64.zip dist/*

      - name: Create Dev Build Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/dev-')
        with:
          prerelease: true
          generate_release_notes: false
          body: "This is a dev build. It very likely contains bugs and is not recommended for use."
          files: bsw-x86_64.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
          files: bsw-x86_64.zip
